### ISSUE TITLE
deploy repository and install local library

### ISSUE THREAD

**Issue by apatlpo** [pangeo-data/pangeo-binder-template#6]
I'm struggling with an issue that may be very silly, apologies:

I copied pangeo-binder-template into a [repository](https://github.com/apatlpo/cognac) I'd like to deploy on mybinder.
When deploying the repository I'd like the local library (`cognac`) to be installed as well but fail to do this at the moment.
Would you have recommendations as how to do this?

**Comment by rabernat** [comment]
This is not very well documented, so your confusion is not silly at all!

The gallery distinguishes between the **binder repo** and the **code repo**. The binder repo stores the environment, while the code repo stores the notebook. The point of doing this is so we don't have to rebuild the environment every time the code changes.

If you want to use a binder repo other than `pangeo-data/default-binder`, you'll have to edit `binder-gallery.yaml`, according to [these instructions](http://gallery.pangeo.io/contributing.html#config-file-specification) and create a custom binder environment with your desired packages in the binder repo.

If you want to keep your binder repo and code repo in the same github repo, they should be on different branches. You can see an example of this here: https://github.com/rsignell-usgs/esip-gallery/blob/master/binder-gallery.yaml
```yaml
---
name: ESIP Gallery
description: >-
  An gallery of notebooks developed by ESIP Collaborators
gallery_repository: pangeo-gallery/pangeo-gallery
binder_url: "https://aws-uswest2-binder.pangeo.io"
binder_repo: rsignell-usgs/esip-gallery
binder_ref: binder
binderbot_target_branch: binderbot-built
```

The binder repo is on the `binder` branch of `rsignell-usgs/esip-gallery`: https://github.com/rsignell-usgs/esip-gallery/tree/binder
